#!/usr/bin/env python3  # 作用: 指定解释器入口; 原理: Shebang告诉系统用哪个解释器; 专业概念: Shebang(脚本首行标识)
import json  # 作用: 处理JSON数据; 原理: 标准库序列化/反序列化; 专业概念: JSON(JavaScript Object Notation, 轻量数据格式)
import os  # 作用: 访问环境变量与文件路径; 原理: 标准库系统接口; 专业概念: OS接口(Operating System Interface, 系统交互)
import time  # 作用: 提供延迟功能; 原理: 标准库时间模块; 专业概念: 休眠(Sleep, 暂停执行)
import csv  # 作用: 生成CSV文件; 原理: 标准库CSV写入器; 专业概念: CSV(逗号分隔值, 表格文本格式)
import random  # 作用: 生成随机数; 原理: 伪随机算法; 专业概念: 伪随机(Pseudo-random, 近似随机)
import string  # 作用: 提供字符集合; 原理: 标准库常量; 专业概念: 字符集(Character Set, 可用字符集合)
import urllib.request  # 作用: 发送HTTP请求; 原理: 标准库网络请求; 专业概念: HTTP客户端(HTTP Client, 发起请求)
import urllib.error  # 作用: 处理HTTP异常; 原理: 标准库异常类型; 专业概念: 异常处理(Exception Handling, 错误控制)


def load_env_file(env_path):  # 作用: 加载.env文件; 原理: 逐行解析键值; 专业概念: 配置文件(Configuration File, 外部参数)
    if not env_path or not os.path.isfile(env_path):  # 作用: 校验文件路径; 原理: 条件判断+文件存在检查; 专业概念: 文件系统(File System)
        return {}  # 作用: 返回空配置; 原理: 早退出; 专业概念: 空字典(Empty Dict, 无内容集合)
    data = {}  # 作用: 初始化配置容器; 原理: 字典存储键值; 专业概念: 字典(Dictionary, 键值映射)
    with open(env_path, "r", encoding="utf-8") as f:  # 作用: 打开文件读取; 原理: 上下文管理自动关闭; 专业概念: 上下文管理(Context Manager)
        for raw in f:  # 作用: 逐行读取; 原理: 迭代器遍历; 专业概念: 迭代(Iteration, 顺序访问)
            line = raw.strip()  # 作用: 去除空白; 原理: 字符串裁剪; 专业概念: 字符串处理(String Processing)
            if not line or line.startswith("#"):  # 作用: 跳过空行/注释; 原理: 条件判断; 专业概念: 注释(Comment, 非执行内容)
                continue  # 作用: 进入下一行; 原理: 循环控制; 专业概念: continue(继续下一次循环)
            if "=" not in line:  # 作用: 过滤非法行; 原理: 字符串包含判断; 专业概念: 格式校验(Validation, 规则检查)
                continue  # 作用: 忽略非法行; 原理: 循环控制; 专业概念: continue(继续下一次循环)
            key, value = line.split("=", 1)  # 作用: 分离键和值; 原理: 字符串分割; 专业概念: 解析(Parse, 结构化读取)
            data[key.strip()] = value.strip()  # 作用: 保存键值; 原理: 字典赋值; 专业概念: 映射(Mapping, 键值对)
    return data  # 作用: 返回配置; 原理: 函数返回值; 专业概念: 返回值(Return Value)


def load_md_defaults(md_path):  # 作用: 读取md里的默认配置; 原理: 按行解析关键字段; 专业概念: 兜底配置(Fallback, 备用来源)
    if not md_path or not os.path.isfile(md_path):  # 作用: 校验md路径; 原理: 文件存在检查; 专业概念: 文件系统(File System)
        return {}  # 作用: 返回空配置; 原理: 早退出; 专业概念: 空字典(Empty Dict)
    data = {}  # 作用: 初始化容器; 原理: 字典存储; 专业概念: 字典(Dictionary)
    with open(md_path, "r", encoding="utf-8") as f:  # 作用: 打开md文件; 原理: 上下文管理; 专业概念: 上下文管理(Context Manager)
        for raw in f:  # 作用: 逐行读取; 原理: 迭代遍历; 专业概念: 迭代(Iteration)
            line = raw.strip()  # 作用: 去除空白; 原理: 字符串裁剪; 专业概念: 字符串处理(String Processing)
            if "API 令牌：" in line:  # 作用: 匹配令牌行; 原理: 子串判断; 专业概念: 模式匹配(Pattern Matching)
                token = line.split("API 令牌：", 1)[1].strip()  # 作用: 提取令牌; 原理: 字符串分割; 专业概念: 解析(Parse)
                if token:  # 作用: 校验令牌非空; 原理: 条件判断; 专业概念: 非空检查(Non-Empty Check)
                    data["CF_API_TOKEN"] = token  # 作用: 记录令牌; 原理: 字典赋值; 专业概念: 键值映射(Mapping)
            if line.startswith("CF_ZONE_ID="):  # 作用: 识别Zone ID; 原理: 前缀匹配; 专业概念: 前缀(StartsWith)
                data["CF_ZONE_ID"] = line.split("=", 1)[1].strip()  # 作用: 提取Zone ID; 原理: 字符串分割; 专业概念: 解析(Parse)
            if line.startswith("CF_DOMAIN="):  # 作用: 识别域名; 原理: 前缀匹配; 专业概念: 前缀(StartsWith)
                data["CF_DOMAIN"] = line.split("=", 1)[1].strip()  # 作用: 提取域名; 原理: 字符串分割; 专业概念: 解析(Parse)
            if line.startswith("CF_DEST_EMAIL="):  # 作用: 识别目标邮箱; 原理: 前缀匹配; 专业概念: 前缀(StartsWith)
                data["CF_DEST_EMAIL"] = line.split("=", 1)[1].strip()  # 作用: 提取目标邮箱; 原理: 字符串分割; 专业概念: 解析(Parse)
    return data  # 作用: 返回配置; 原理: 函数返回; 专业概念: 返回值(Return Value)


def get_config():  # 作用: 获取并合并配置; 原理: 环境变量 > .env > md默认; 专业概念: 配置合并(Configuration Merge)
    env_path = os.getenv("CF_ENV_FILE", ".env")  # 作用: 读取.env路径; 原理: 读取环境变量; 专业概念: 环境变量(Environment Variable)
    file_env = load_env_file(env_path)  # 作用: 读取.env内容; 原理: 调用解析函数; 专业概念: 函数调用(Function Call)
    md_env = load_md_defaults("Cloudflare批量邮箱地址.md")  # 作用: 读取md默认配置; 原理: 解析现有说明文件; 专业概念: 兜底配置(Fallback)
    def pick(key, default=""):  # 作用: 获取配置值; 原理: 本地函数封装; 专业概念: 闭包(Closure, 函数内定义函数)
        return os.getenv(key, file_env.get(key, md_env.get(key, default)))  # 作用: 按优先级取值; 原理: 多源覆盖; 专业概念: 覆盖(Override)
    return {  # 作用: 统一输出配置; 原理: 组装字典; 专业概念: 配置对象(Configuration Object)
        "token": pick("CF_API_TOKEN"),  # 作用: 读取API令牌; 原理: 配置映射; 专业概念: 认证令牌(Token, 访问凭证)
        "zone_id": pick("CF_ZONE_ID"),  # 作用: 读取Zone ID; 原理: 配置映射; 专业概念: 区域ID(Zone ID, 资源标识)
        "account_id": pick("CF_ACCOUNT_ID"),  # 作用: 读取账号ID; 原理: 配置映射; 专业概念: 账号ID(Account ID, 账户标识)
        "domain": pick("CF_DOMAIN"),  # 作用: 读取域名; 原理: 配置映射; 专业概念: 域名(Domain, 站点标识)
        "dest_email": pick("CF_DEST_EMAIL"),  # 作用: 读取目标邮箱; 原理: 配置映射; 专业概念: 目标地址(Destination, 转发终点)
        "input_file": pick("CF_INPUT_FILE"),  # 作用: 读取输入文件路径; 原理: 配置映射; 专业概念: 文件路径(File Path)
        "prefix": pick("CF_PREFIX"),  # 作用: 读取地址前缀; 原理: 配置映射; 专业概念: 前缀(Prefix, 文本前置部分)
        "start": pick("CF_START", "1"),  # 作用: 读取起始序号; 原理: 配置映射; 专业概念: 起始值(Start, 序列起点)
        "count": pick("CF_COUNT", "5"),  # 作用: 读取生成数量; 原理: 配置映射; 专业概念: 计数(Count, 数量)
        "delay_ms": pick("CF_DELAY_MS", "0"),  # 作用: 读取延迟毫秒; 原理: 配置映射; 专业概念: 节流(Throttling, 控制频率)
        "rule_enabled": pick("CF_RULE_ENABLED", "true"),  # 作用: 读取规则启用; 原理: 配置映射; 专业概念: 开关(Switch, 布尔控制)
        "output_csv": pick("CF_OUTPUT_CSV", "result.csv"),  # 作用: 读取输出CSV路径; 原理: 配置映射; 专业概念: 输出文件(Output File)
    }  # 作用: 结束配置字典; 原理: 字面量结束; 专业概念: 字典字面量(Dictionary Literal)


def random_local_part(length=8):  # 作用: 生成随机本地部分; 原理: 随机抽样; 专业概念: 随机字符串(Random String, 随机文本)
    alphabet = string.ascii_lowercase + string.digits  # 作用: 定义字符集; 原理: 字符串拼接; 专业概念: 字符集(Character Set)
    return "".join(random.choice(alphabet) for _ in range(length))  # 作用: 生成随机字符串; 原理: 迭代拼接; 专业概念: 列表推导(Comprehension)


def parse_int(value, name):  # 作用: 解析整数; 原理: 类型转换; 专业概念: 类型转换(Type Casting)
    try:  # 作用: 捕获转换错误; 原理: try/except结构; 专业概念: 异常处理(Exception Handling)
        return int(value)  # 作用: 转成整数; 原理: 内建类型转换; 专业概念: 整数(Integer, 整数类型)
    except ValueError as exc:  # 作用: 捕获格式错误; 原理: 异常分支; 专业概念: ValueError(值错误)
        raise ValueError(f"{name} 必须是整数") from exc  # 作用: 抛出友好错误; 原理: 异常链; 专业概念: 异常链(Chaining)


def load_addresses(cfg):  # 作用: 生成地址列表; 原理: 文件读取或前缀生成; 专业概念: 地址列表(Address List)
    addresses = []  # 作用: 初始化列表; 原理: 列表容器; 专业概念: 列表(List, 有序集合)
    input_file = cfg["input_file"]  # 作用: 获取输入文件; 原理: 字典取值; 专业概念: 键值访问(Key Access)
    domain = cfg["domain"]  # 作用: 获取域名; 原理: 字典取值; 专业概念: 键值访问(Key Access)
    if input_file:  # 作用: 判断是否文件模式; 原理: 条件判断; 专业概念: 条件分支(Condition)
        if not os.path.isfile(input_file):  # 作用: 校验文件存在; 原理: 文件系统检查; 专业概念: 文件系统(File System)
            raise FileNotFoundError(f"找不到输入文件: {input_file}")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: FileNotFoundError(文件不存在)
        with open(input_file, "r", encoding="utf-8") as f:  # 作用: 打开文件读取; 原理: 上下文管理; 专业概念: 上下文管理(Context Manager)
            for raw in f:  # 作用: 逐行读取; 原理: 迭代遍历; 专业概念: 迭代(Iteration)
                line = raw.strip()  # 作用: 去除空白; 原理: 字符串裁剪; 专业概念: 字符串处理(String Processing)
                if not line:  # 作用: 跳过空行; 原理: 条件判断; 专业概念: 空值检查(Empty Check)
                    continue  # 作用: 跳到下一行; 原理: 循环控制; 专业概念: continue(继续)
                if "@" in line:  # 作用: 判断是否完整邮箱; 原理: 字符串包含判断; 专业概念: 邮箱格式(Email Format)
                    address = line  # 作用: 使用完整邮箱; 原理: 直接赋值; 专业概念: 变量赋值(Assignment)
                else:  # 作用: 处理本地部分; 原理: 条件分支; 专业概念: 本地部分(Local Part, @前内容)
                    if not domain:  # 作用: 校验域名存在; 原理: 条件判断; 专业概念: 必填校验(Required Check)
                        raise ValueError("输入文件含本地部分但未设置 CF_DOMAIN")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
                    address = f"{line}@{domain}"  # 作用: 拼接邮箱; 原理: 字符串插值; 专业概念: 字符串插值(String Interpolation)
                addresses.append(address)  # 作用: 追加地址; 原理: 列表追加; 专业概念: 追加(Append)
    else:  # 作用: 使用前缀或随机模式; 原理: 条件分支; 专业概念: 模式切换(Mode Switch)
        if not domain:  # 作用: 校验域名存在; 原理: 条件判断; 专业概念: 必填校验(Required Check)
            raise ValueError("使用前缀生成时必须设置 CF_DOMAIN")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
        prefix = cfg["prefix"]  # 作用: 获取前缀; 原理: 字典取值; 专业概念: 键值访问(Key Access)
        start = parse_int(cfg["start"], "CF_START")  # 作用: 解析起始序号; 原理: 调用整型解析; 专业概念: 序号(Index)
        count = parse_int(cfg["count"], "CF_COUNT")  # 作用: 解析数量; 原理: 调用整型解析; 专业概念: 数量(Count)
        if count <= 0:  # 作用: 校验数量为正; 原理: 数值比较; 专业概念: 边界检查(Boundary Check)
            raise ValueError("CF_COUNT 必须为正数")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
        for i in range(count):  # 作用: 生成序列; 原理: for循环计数; 专业概念: for循环(For Loop)
            num = start + i  # 作用: 计算序号; 原理: 算术运算; 专业概念: 加法(Addition)
            if prefix:  # 作用: 判断是否有前缀; 原理: 条件判断; 专业概念: 条件分支(Condition)
                local_part = f"{prefix}{num}"  # 作用: 生成本地部分; 原理: 字符串插值; 专业概念: 本地部分(Local Part)
            else:  # 作用: 无前缀时用随机本地部分; 原理: 条件分支; 专业概念: 随机生成(Random Generation)
                local_part = random_local_part()  # 作用: 生成随机本地部分; 原理: 调用随机函数; 专业概念: 随机字符串(Random String)
            address = f"{local_part}@{domain}"  # 作用: 拼接邮箱; 原理: 字符串插值; 专业概念: 字符串插值(String Interpolation)
            addresses.append(address)  # 作用: 追加地址; 原理: 列表追加; 专业概念: 追加(Append)
    if not addresses:  # 作用: 校验列表非空; 原理: 条件判断; 专业概念: 非空检查(Non-Empty Check)
        raise ValueError("未生成任何地址")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
    return addresses  # 作用: 返回地址列表; 原理: 函数返回; 专业概念: 返回值(Return Value)


def build_rule_body(address, dest_email, enabled):  # 作用: 构造规则请求体; 原理: 组装JSON结构; 专业概念: 请求体(Request Body)
    return {  # 作用: 返回规则结构; 原理: 字典字面量; 专业概念: 数据结构(Data Structure)
        "name": f"bulk:{address}",  # 作用: 规则名称; 原理: 字符串插值; 专业概念: 命名(Naming)
        "enabled": enabled,  # 作用: 规则开关; 原理: 布尔赋值; 专业概念: 布尔值(Boolean)
        "matchers": [  # 作用: 设置匹配器列表; 原理: 列表包含字典; 专业概念: 匹配器(Matcher)
            {  # 作用: 单条匹配器; 原理: 字典结构; 专业概念: 条件(Condition)
                "type": "literal",  # 作用: 精确匹配; 原理: 固定值; 专业概念: 字面量(Literal)
                "field": "to",  # 作用: 匹配收件人字段; 原理: 固定值; 专业概念: 字段(Field)
                "value": address,  # 作用: 匹配具体地址; 原理: 变量引用; 专业概念: 值(Value)
            }  # 作用: 结束匹配器; 原理: 结构结束; 专业概念: 结构体(Structure)
        ],  # 作用: 结束匹配器列表; 原理: 列表结束; 专业概念: 列表(List)
        "actions": [  # 作用: 设置动作列表; 原理: 列表包含字典; 专业概念: 动作(Action)
            {  # 作用: 单条动作; 原理: 字典结构; 专业概念: 动作(Action)
                "type": "forward",  # 作用: 指定转发; 原理: 固定值; 专业概念: 转发(Forwarding)
                "value": [dest_email],  # 作用: 指定目标邮箱; 原理: 列表包裹; 专业概念: 目标列表(Destination List)
            }  # 作用: 结束动作; 原理: 结构结束; 专业概念: 结构体(Structure)
        ],  # 作用: 结束动作列表; 原理: 列表结束; 专业概念: 列表(List)
    }  # 作用: 结束请求体; 原理: 结构结束; 专业概念: 对象(Object)


def post_json(url, token, payload):  # 作用: 发送POST请求; 原理: HTTP请求+JSON序列化; 专业概念: REST API(接口调用)
    data = json.dumps(payload).encode("utf-8")  # 作用: 序列化为JSON字节; 原理: JSON编码; 专业概念: 序列化(Serialization)
    req = urllib.request.Request(url, data=data, method="POST")  # 作用: 构造请求对象; 原理: HTTP请求封装; 专业概念: 请求对象(Request Object)
    req.add_header("Authorization", f"Bearer {token}")  # 作用: 添加认证头; 原理: Bearer认证; 专业概念: 认证(Authorization)
    req.add_header("Content-Type", "application/json")  # 作用: 指定内容类型; 原理: HTTP头; 专业概念: MIME类型(MIME Type)
    try:  # 作用: 捕获HTTP异常; 原理: try/except结构; 专业概念: 异常处理(Exception Handling)
        with urllib.request.urlopen(req, timeout=30) as resp:  # 作用: 发起请求并读取响应; 原理: URL打开器; 专业概念: 超时(Timeout)
            body = resp.read().decode("utf-8")  # 作用: 读取响应内容; 原理: 字节转字符串; 专业概念: 解码(Decoding)
            return json.loads(body)  # 作用: 解析JSON响应; 原理: JSON反序列化; 专业概念: 反序列化(Deserialization)
    except urllib.error.HTTPError as exc:  # 作用: 捕获HTTP错误; 原理: 异常分支; 专业概念: HTTPError(HTTP错误)
        detail = exc.read().decode("utf-8")  # 作用: 读取错误响应; 原理: 读取错误流; 专业概念: 错误响应(Error Response)
        raise RuntimeError(detail) from exc  # 作用: 抛出运行错误; 原理: 异常包装; 专业概念: 异常包装(Exception Wrapping)


def load_existing_records(csv_path):  # 作用: 加载现有CSV记录; 原理: 读取并保留历史数据; 专业概念: 数据持久化(Data Persistence)
    if not os.path.isfile(csv_path):  # 作用: 检查文件是否存在; 原理: 文件系统检查; 专业概念: 文件存在性(File Existence)
        return {}  # 作用: 返回空字典; 原理: 无历史记录时返回空容器; 专业概念: 空字典(Empty Dict)
    records = {}  # 作用: 初始化记录字典; 原理: 用地址作为键存储记录; 专业概念: 字典映射(Dictionary Mapping)
    with open(csv_path, "r", encoding="utf-8") as f:  # 作用: 打开CSV文件读取; 原理: 上下文管理; 专业概念: 上下文管理(Context Manager)
        reader = csv.DictReader(f)  # 作用: 创建字典读取器; 原理: CSV解析为字典; 专业概念: DictReader(字典读取器)
        for row in reader:  # 作用: 逐行读取; 原理: 迭代遍历; 专业概念: 迭代(Iteration)
            address = row.get("address", "").strip()  # 作用: 获取邮箱地址; 原理: 字典取值并去空白; 专业概念: 数据清洗(Data Cleaning)
            if address:  # 作用: 过滤空地址; 原理: 条件判断; 专业概念: 非空检查(Non-Empty Check)
                records[address] = row  # 作用: 保存记录; 原理: 字典赋值; 专业概念: 键值映射(Key-Value Mapping)
    return records  # 作用: 返回记录字典; 原理: 函数返回; 专业概念: 返回值(Return Value)


def merge_records(existing, new_results, created_date):  # 作用: 合并新旧记录; 原理: 保留历史+追加新记录; 专业概念: 数据合并(Data Merging)
    merged = existing.copy()  # 作用: 复制现有记录; 原理: 浅拷贝避免修改原数据; 专业概念: 拷贝(Copy)
    for result in new_results:  # 作用: 遍历新结果; 原理: 循环处理; 专业概念: 迭代(Iteration)
        address = result["address"]  # 作用: 获取邮箱地址; 原理: 字典取值; 专业概念: 键访问(Key Access)
        if address in merged:  # 作用: 检查是否已存在; 原理: 字典成员判断; 专业概念: 成员检查(Membership Test)
            # 作用: 更新已有记录; 原理: 覆盖旧状态; 专业概念: 更新(Update)
            merged[address]["status"] = result["status"]  # 作用: 更新状态; 原理: 字典赋值; 专业概念: 状态更新(Status Update)
            merged[address]["message"] = result["message"]  # 作用: 更新消息; 原理: 字典赋值; 专业概念: 消息更新(Message Update)
        else:  # 作用: 新增记录; 原理: 插入新键值; 专业概念: 插入(Insert)
            merged[address] = {  # 作用: 构建新记录; 原理: 字典字面量; 专业概念: 记录对象(Record Object)
                "address": address,  # 作用: 邮箱地址; 原理: 字段赋值; 专业概念: 字段(Field)
                "created_date": created_date,  # 作用: 生成日期; 原理: 时间戳记录; 专业概念: 时间戳(Timestamp)
                "status": result["status"],  # 作用: 创建状态; 原理: 状态记录; 专业概念: 状态(Status)
                "message": result["message"],  # 作用: 错误信息; 原理: 消息记录; 专业概念: 消息(Message)
                "is_deleted": "否",  # 作用: 删除标记; 原理: 布尔字段文本化; 专业概念: 标记位(Flag)
                "deleted_date": "",  # 作用: 删除日期; 原理: 预留字段; 专业概念: 预留字段(Reserved Field)
            }
    return list(merged.values())  # 作用: 转换为列表; 原理: 字典值转列表; 专业概念: 值列表(Values List)


def main():  # 作用: 程序入口; 原理: 主函数组织流程; 专业概念: 主函数(Main Function)
    from datetime import datetime  # 作用: 导入日期时间模块; 原理: 获取当前时间; 专业概念: 日期时间(Datetime)
    cfg = get_config()  # 作用: 读取配置; 原理: 调用配置函数; 专业概念: 配置读取(Configuration Load)
    required = ["token", "zone_id", "dest_email"]  # 作用: 定义必填项; 原理: 列表常量; 专业概念: 必填字段(Required Fields)
    for key in required:  # 作用: 遍历必填项; 原理: 循环检查; 专业概念: 校验(Validation)
        if not cfg[key]:  # 作用: 判断缺失; 原理: 条件判断; 专业概念: 空值(Empty Value)
            raise ValueError(f"请设置 {key}")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
    addresses = load_addresses(cfg)  # 作用: 生成地址列表; 原理: 调用地址生成; 专业概念: 数据准备(Data Preparation)
    enabled = cfg["rule_enabled"].lower() != "false"  # 作用: 解析启用开关; 原理: 字符串比较; 专业概念: 布尔解析(Boolean Parse)
    delay_ms = parse_int(cfg["delay_ms"], "CF_DELAY_MS")  # 作用: 解析延迟; 原理: 整数转换; 专业概念: 节流(Throttling)
    api_base = "https://api.cloudflare.com/client/v4"  # 作用: 定义API基础地址; 原理: 常量配置; 专业概念: 端点(Endpoint)
    endpoint = f"{api_base}/zones/{cfg['zone_id']}/email/routing/rules"  # 作用: 拼接接口路径; 原理: 字符串插值; 专业概念: API路径(API Path)
    created_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # 作用: 获取当前时间; 原理: 格式化时间戳; 专业概念: 时间格式化(Time Formatting)
    results = []  # 作用: 存放结果列表; 原理: 列表容器; 专业概念: 结果集(Result Set)
    for address in addresses:  # 作用: 遍历地址创建规则; 原理: 循环处理; 专业概念: 批处理(Batch Processing)
        payload = build_rule_body(address, cfg["dest_email"], enabled)  # 作用: 构造请求体; 原理: 函数组装; 专业概念: 请求体(Request Body)
        try:  # 作用: 捕获单条请求错误; 原理: try/except; 专业概念: 异常处理(Exception Handling)
            resp = post_json(endpoint, cfg["token"], payload)  # 作用: 调用API; 原理: HTTP POST; 专业概念: REST调用(REST Call)
            if resp.get("success") is True:  # 作用: 判断是否成功; 原理: 读取响应字段; 专业概念: 响应结构(Response Schema)
                print(f"OK: {address}")  # 作用: 输出成功; 原理: 标准输出; 专业概念: 标准输出(stdout)
                results.append({"address": address, "status": "OK", "message": ""})  # 作用: 记录成功结果; 原理: 字典追加; 专业概念: 结果记录(Result Record)
            else:  # 作用: 处理失败; 原理: 条件分支; 专业概念: 错误处理(Error Handling)
                print(f"FAIL: {address}")  # 作用: 输出失败; 原理: 标准输出; 专业概念: 标准输出(stdout)
                errors_text = json.dumps(resp.get("errors", []), ensure_ascii=False)  # 作用: 格式化错误详情; 原理: JSON序列化; 专业概念: 诊断信息(Diagnostics)
                print(errors_text)  # 作用: 输出错误详情; 原理: 标准输出; 专业概念: 标准输出(stdout)
                results.append({"address": address, "status": "FAIL", "message": errors_text})  # 作用: 记录失败结果; 原理: 字典追加; 专业概念: 结果记录(Result Record)
        except Exception as exc:  # 作用: 捕获异常; 原理: 异常兜底; 专业概念: 兜底异常(General Exception)
            print(f"ERROR: {address}")  # 作用: 输出异常提示; 原理: 标准输出; 专业概念: 标准输出(stdout)
            error_text = str(exc)  # 作用: 转成异常文本; 原理: 字符串转换; 专业概念: 异常消息(Exception Message)
            print(error_text)  # 作用: 输出异常信息; 原理: 标准输出; 专业概念: 标准输出(stdout)
            results.append({"address": address, "status": "ERROR", "message": error_text})  # 作用: 记录异常结果; 原理: 字典追加; 专业概念: 结果记录(Result Record)
        if delay_ms > 0:  # 作用: 判断是否延迟; 原理: 数值比较; 专业概念: 节流(Throttling)
            time.sleep(delay_ms / 1000.0)  # 作用: 进行延迟; 原理: 秒级休眠; 专业概念: 休眠(Sleep)
    output_csv = cfg["output_csv"]  # 作用: 获取CSV输出路径; 原理: 字典取值; 专业概念: 路径(Path)
    existing_records = load_existing_records(output_csv)  # 作用: 加载现有记录; 原理: 读取历史CSV; 专业概念: 数据加载(Data Loading)
    all_records = merge_records(existing_records, results, created_date)  # 作用: 合并新旧记录; 原理: 数据合并; 专业概念: 数据合并(Data Merging)
    with open(output_csv, "w", encoding="utf-8", newline="") as f:  # 作用: 打开CSV文件写入; 原理: 上下文管理; 专业概念: 文件IO(File I/O)
        fieldnames = ["address", "created_date", "status", "message", "is_deleted", "deleted_date"]  # 作用: 定义CSV字段; 原理: 字段列表; 专业概念: 表结构(Schema)
        writer = csv.DictWriter(f, fieldnames=fieldnames)  # 作用: 创建CSV写入器; 原理: 字段映射; 专业概念: 字段(Field)
        writer.writeheader()  # 作用: 写入表头; 原理: CSV写入; 专业概念: 表头(Header)
        writer.writerows(all_records)  # 作用: 写入所有结果; 原理: 批量写入; 专业概念: 批处理(Batch Write)
    print(f"CSV 已更新: {output_csv}")  # 作用: 输出CSV路径; 原理: 标准输出; 专业概念: 标准输出(stdout)
    print(f"本次新增: {len(results)} 条记录")  # 作用: 输出统计信息; 原理: 列表长度; 专业概念: 统计(Statistics)
    print(f"总计记录: {len(all_records)} 条")  # 作用: 输出总计数; 原理: 列表长度; 专业概念: 统计(Statistics)


if __name__ == "__main__":  # 作用: 判断是否主模块; 原理: Python入口判断; 专业概念: 主模块(Main Module)
    main()  # 作用: 调用主函数; 原理: 函数调用; 专业概念: 程序入口(Entry Point)
