#!/usr/bin/env python3  # 作用: 指定解释器入口; 原理: Shebang告诉系统用哪个解释器; 专业概念: Shebang(脚本首行标识)
import csv  # 作用: 读取CSV文件; 原理: 标准库CSV解析; 专业概念: CSV(逗号分隔值, 表格文本格式)
import json  # 作用: 处理JSON数据; 原理: 标准库序列化/反序列化; 专业概念: JSON(JavaScript Object Notation, 轻量数据格式)
import os  # 作用: 访问环境变量与文件路径; 原理: 标准库系统接口; 专业概念: OS接口(Operating System Interface, 系统交互)
import urllib.request  # 作用: 发送HTTP请求; 原理: 标准库网络请求; 专业概念: HTTP客户端(HTTP Client, 发起请求)
import urllib.error  # 作用: 处理HTTP异常; 原理: 标准库异常类型; 专业概念: 异常处理(Exception Handling, 错误控制)


def load_env_file(env_path):  # 作用: 加载.env文件; 原理: 逐行解析键值; 专业概念: 配置文件(Configuration File, 外部参数)
    if not env_path or not os.path.isfile(env_path):  # 作用: 校验文件路径; 原理: 条件判断+文件存在检查; 专业概念: 文件系统(File System)
        return {}  # 作用: 返回空配置; 原理: 早退出; 专业概念: 空字典(Empty Dict)
    data = {}  # 作用: 初始化配置容器; 原理: 字典存储键值; 专业概念: 字典(Dictionary)
    with open(env_path, "r", encoding="utf-8") as f:  # 作用: 打开文件读取; 原理: 上下文管理; 专业概念: 上下文管理(Context Manager)
        for raw in f:  # 作用: 逐行读取; 原理: 迭代遍历; 专业概念: 迭代(Iteration)
            line = raw.strip()  # 作用: 去除空白; 原理: 字符串裁剪; 专业概念: 字符串处理(String Processing)
            if not line or line.startswith("#"):  # 作用: 跳过空行/注释; 原理: 条件判断; 专业概念: 注释(Comment, 非执行内容)
                continue  # 作用: 进入下一行; 原理: 循环控制; 专业概念: continue(继续)
            if "=" not in line:  # 作用: 过滤非法行; 原理: 字符串包含判断; 专业概念: 格式校验(Validation)
                continue  # 作用: 忽略非法行; 原理: 循环控制; 专业概念: continue(继续)
            key, value = line.split("=", 1)  # 作用: 分离键和值; 原理: 字符串分割; 专业概念: 解析(Parse)
            data[key.strip()] = value.strip()  # 作用: 保存键值; 原理: 字典赋值; 专业概念: 映射(Mapping)
    return data  # 作用: 返回配置; 原理: 函数返回; 专业概念: 返回值(Return Value)


def get_config():  # 作用: 获取配置; 原理: 环境变量优先+ .env 兜底; 专业概念: 配置合并(Configuration Merge)
    env_path = os.getenv("CF_ENV_FILE", ".env")  # 作用: 读取.env路径; 原理: 读取环境变量; 专业概念: 环境变量(Environment Variable)
    file_env = load_env_file(env_path)  # 作用: 读取.env内容; 原理: 调用解析函数; 专业概念: 函数调用(Function Call)
    def pick(key, default=""):  # 作用: 获取配置值; 原理: 本地函数封装; 专业概念: 闭包(Closure)
        return os.getenv(key, file_env.get(key, default))  # 作用: 按优先级取值; 原理: 覆盖; 专业概念: 覆盖(Override)
    return {  # 作用: 统一输出配置; 原理: 字典组装; 专业概念: 配置对象(Configuration Object)
        "token": pick("CF_API_TOKEN"),  # 作用: 读取API令牌; 原理: 配置映射; 专业概念: 认证令牌(Token)
        "zone_id": pick("CF_ZONE_ID"),  # 作用: 读取Zone ID; 原理: 配置映射; 专业概念: 区域ID(Zone ID)
        "delete_mode": pick("CF_DELETE_MODE"),  # 作用: 删除模式; 原理: 配置映射; 专业概念: 模式(Mode)
        "delete_csv": pick("CF_DELETE_CSV", "result.csv"),  # 作用: CSV路径; 原理: 配置映射; 专业概念: 文件路径(Path)
        "delete_addresses": pick("CF_DELETE_ADDRESSES"),  # 作用: 指定地址; 原理: 配置映射; 专业概念: 地址列表(Address List)
        "delete_date": pick("CF_DELETE_DATE"),  # 作用: 指定删除日期; 原理: 配置映射; 专业概念: 日期过滤(Date Filter)
    }  # 作用: 结束配置字典; 原理: 字面量结束; 专业概念: 字典(Dictionary)


def request_json(url, token, method="GET"):  # 作用: 发送HTTP请求; 原理: urllib封装请求; 专业概念: HTTP请求(HTTP Request)
    req = urllib.request.Request(url, method=method)  # 作用: 构造请求对象; 原理: 请求封装; 专业概念: 请求对象(Request Object)
    req.add_header("Authorization", f"Bearer {token}")  # 作用: 添加认证头; 原理: Bearer认证; 专业概念: 认证(Authorization)
    req.add_header("Content-Type", "application/json")  # 作用: 指定内容类型; 原理: HTTP头; 专业概念: MIME类型(MIME Type)
    try:  # 作用: 捕获HTTP异常; 原理: try/except; 专业概念: 异常处理(Exception Handling)
        with urllib.request.urlopen(req, timeout=30) as resp:  # 作用: 发起请求并读取响应; 原理: URL打开器; 专业概念: 超时(Timeout)
            body = resp.read().decode("utf-8")  # 作用: 读取响应内容; 原理: 解码; 专业概念: 解码(Decoding)
            return json.loads(body)  # 作用: 解析JSON; 原理: 反序列化; 专业概念: 反序列化(Deserialization)
    except urllib.error.HTTPError as exc:  # 作用: 捕获HTTP错误; 原理: 异常分支; 专业概念: HTTPError(HTTP错误)
        detail = exc.read().decode("utf-8")  # 作用: 读取错误响应; 原理: 读取错误流; 专业概念: 错误响应(Error Response)
        raise RuntimeError(detail) from exc  # 作用: 抛出运行错误; 原理: 异常包装; 专业概念: 异常包装(Exception Wrapping)


def list_rules(token, zone_id):  # 作用: 拉取全部规则; 原理: 分页请求; 专业概念: 分页(Pagination)
    api_base = "https://api.cloudflare.com/client/v4"  # 作用: API基础地址; 原理: 常量配置; 专业概念: 端点(Endpoint)
    page = 1  # 作用: 初始化页码; 原理: 变量赋值; 专业概念: 页码(Page)
    per_page = 50  # 作用: 设置每页数量; 原理: 常量; 专业概念: 分页大小(Page Size)
    rules = []  # 作用: 收集规则; 原理: 列表容器; 专业概念: 列表(List)
    while True:  # 作用: 轮询分页; 原理: 循环; 专业概念: while循环(While Loop)
        url = f"{api_base}/zones/{zone_id}/email/routing/rules?page={page}&per_page={per_page}"  # 作用: 拼接列表接口; 原理: 字符串插值; 专业概念: API路径(API Path)
        resp = request_json(url, token, method="GET")  # 作用: 请求规则列表; 原理: HTTP GET; 专业概念: REST调用(REST Call)
        items = resp.get("result", [])  # 作用: 读取结果; 原理: 字典取值; 专业概念: 响应体(Response Body)
        rules.extend(items)  # 作用: 合并规则; 原理: 列表扩展; 专业概念: 扩展(Extend)
        result_info = resp.get("result_info", {})  # 作用: 读取分页信息; 原理: 字典取值; 专业概念: 元数据(Metadata)
        total_pages = result_info.get("total_pages", page)  # 作用: 获取总页数; 原理: 字典取值; 专业概念: 总页数(Total Pages)
        if page >= total_pages:  # 作用: 判断是否结束; 原理: 比较; 专业概念: 终止条件(Termination Condition)
            break  # 作用: 退出循环; 原理: 循环控制; 专业概念: break(跳出循环)
        page += 1  # 作用: 下一页; 原理: 递增; 专业概念: 自增(Increment)
    return rules  # 作用: 返回规则列表; 原理: 函数返回; 专业概念: 返回值(Return Value)


def match_rule_address(rule):  # 作用: 提取规则地址; 原理: 读取matchers; 专业概念: 匹配器(Matcher)
    for matcher in rule.get("matchers", []):  # 作用: 遍历匹配器; 原理: 循环; 专业概念: 迭代(Iteration)
        if matcher.get("field") == "to" and matcher.get("type") == "literal":  # 作用: 过滤收件人匹配; 原理: 条件判断; 专业概念: 过滤(Filter)
            return matcher.get("value", "")  # 作用: 返回地址; 原理: 字典取值; 专业概念: 值(Value)
    return ""  # 作用: 无匹配返回空; 原理: 默认返回; 专业概念: 默认值(Default)


def delete_rule(token, zone_id, rule_id):  # 作用: 删除单条规则; 原理: HTTP DELETE; 专业概念: 删除(Delete)
    api_base = "https://api.cloudflare.com/client/v4"  # 作用: API基础地址; 原理: 常量配置; 专业概念: 端点(Endpoint)
    url = f"{api_base}/zones/{zone_id}/email/routing/rules/{rule_id}"  # 作用: 拼接删除接口; 原理: 字符串插值; 专业概念: API路径(API Path)
    return request_json(url, token, method="DELETE")  # 作用: 发起删除; 原理: HTTP DELETE; 专业概念: REST调用(REST Call)


def load_addresses_from_csv(csv_path, filter_date=None):  # 作用: 读取CSV地址并支持日期过滤; 原理: CSV解析+条件过滤; 专业概念: CSV解析(Parsing)
    if not csv_path or not os.path.isfile(csv_path):  # 作用: 校验CSV存在; 原理: 文件检查; 专业概念: 文件系统(File System)
        raise FileNotFoundError(f"找不到CSV文件: {csv_path}")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: FileNotFoundError(文件不存在)
    addresses = []  # 作用: 初始化地址列表; 原理: 列表容器; 专业概念: 列表(List)
    all_records = []  # 作用: 保存所有记录用于后续更新; 原理: 列表容器; 专业概念: 数据缓存(Data Cache)
    with open(csv_path, "r", encoding="utf-8") as f:  # 作用: 打开CSV; 原理: 上下文管理; 专业概念: 上下文管理(Context Manager)
        reader = csv.DictReader(f)  # 作用: 读取CSV; 原理: 字典读取器; 专业概念: DictReader(字典读取器)
        for row in reader:  # 作用: 逐行读取; 原理: 迭代遍历; 专业概念: 迭代(Iteration)
            all_records.append(row)  # 作用: 保存所有行; 原理: 列表追加; 专业概念: 数据缓存(Data Cache)
            address = (row.get("address") or "").strip()  # 作用: 获取地址字段; 原理: 字典取值; 专业概念: 字段(Field)
            is_deleted = (row.get("is_deleted") or "").strip()  # 作用: 获取删除状态; 原理: 字典取值; 专业概念: 状态字段(Status Field)
            created_date = (row.get("created_date") or "").strip()  # 作用: 获取生成日期; 原理: 字典取值; 专业概念: 时间戳字段(Timestamp Field)
            if not address or is_deleted == "是":  # 作用: 跳过空地址或已删除记录; 原理: 条件判断; 专业概念: 过滤(Filter)
                continue  # 作用: 跳过当前记录; 原理: 循环控制; 专业概念: continue(继续)
            if filter_date:  # 作用: 按日期过滤; 原理: 条件判断; 专业概念: 日期过滤(Date Filter)
                if created_date.startswith(filter_date):  # 作用: 匹配日期前缀; 原理: 字符串前缀匹配; 专业概念: 前缀匹配(Prefix Match)
                    addresses.append(address)  # 作用: 追加符合条件的地址; 原理: 列表追加; 专业概念: 追加(Append)
            else:  # 作用: 无日期过滤时添加所有未删除地址; 原理: 条件分支; 专业概念: 全量加载(Full Load)
                addresses.append(address)  # 作用: 追加地址; 原理: 列表追加; 专业概念: 追加(Append)
    return addresses, all_records  # 作用: 返回地址列表和全部记录; 原理: 元组返回; 专业概念: 多返回值(Multiple Returns)


def parse_address_list(raw):  # 作用: 解析指定地址列表; 原理: 逗号分割; 专业概念: 分隔符(Delimiter)
    if not raw:  # 作用: 处理空输入; 原理: 条件判断; 专业概念: 空值(Empty)
        return []  # 作用: 返回空列表; 原理: 默认返回; 专业概念: 默认值(Default)
    parts = [p.strip() for p in raw.split(",")]  # 作用: 拆分并去空白; 原理: 列表推导; 专业概念: 列表推导(Comprehension)
    return [p for p in parts if p]  # 作用: 过滤空项; 原理: 条件过滤; 专业概念: 过滤(Filter)


def main():  # 作用: 程序入口; 原理: 主函数组织流程; 专业概念: 主函数(Main Function)
    from datetime import datetime  # 作用: 导入日期时间模块; 原理: 获取当前时间; 专业概念: 日期时间(Datetime)
    cfg = get_config()  # 作用: 读取配置; 原理: 调用配置函数; 专业概念: 配置读取(Configuration Load)
    if not cfg["token"] or not cfg["zone_id"]:  # 作用: 校验必填项; 原理: 条件判断; 专业概念: 必填校验(Required Check)
        raise ValueError("请设置 CF_API_TOKEN 和 CF_ZONE_ID")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
    mode = (cfg["delete_mode"] or "").lower()  # 作用: 读取删除模式; 原理: 字符串归一化; 专业概念: 归一化(Normalization)
    if mode not in {"all", "csv", "addresses", "date"}:  # 作用: 校验模式; 原理: 集合判断; 专业概念: 白名单(Allowlist)
        raise ValueError("CF_DELETE_MODE 需为 all / csv / addresses / date")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
    rules = list_rules(cfg["token"], cfg["zone_id"])  # 作用: 获取规则列表; 原理: 分页拉取; 专业概念: 分页(Pagination)
    address_to_rule = {}  # 作用: 构建地址映射; 原理: 字典存储; 专业概念: 映射(Mapping)
    for rule in rules:  # 作用: 遍历规则; 原理: 迭代; 专业概念: 迭代(Iteration)
        addr = match_rule_address(rule)  # 作用: 提取地址; 原理: 读取matchers; 专业概念: 匹配器(Matcher)
        rule_id = rule.get("id")  # 作用: 读取规则ID; 原理: 字典取值; 专业概念: 标识符(Identifier)
        if addr and rule_id:  # 作用: 校验字段完整; 原理: 条件判断; 专业概念: 完整性检查(Integrity Check)
            address_to_rule[addr] = rule_id  # 作用: 建立映射; 原理: 字典赋值; 专业概念: 映射(Mapping)

    all_records = []  # 作用: 初始化所有记录; 原理: 列表容器; 专业概念: 数据容器(Data Container)
    if mode == "all":  # 作用: 删除所有规则; 原理: 条件分支; 专业概念: 全量删除(Full Delete)
        targets = list(address_to_rule.items())  # 作用: 获取全部映射; 原理: 字典转列表; 专业概念: 元组列表(Tuple List)
    elif mode == "date":  # 作用: 按日期删除; 原理: 条件分支; 专业概念: 日期过滤(Date Filter)
        filter_date = cfg["delete_date"]  # 作用: 获取过滤日期; 原理: 字典取值; 专业概念: 日期参数(Date Parameter)
        if not filter_date:  # 作用: 校验日期参数; 原理: 条件判断; 专业概念: 参数校验(Parameter Validation)
            raise ValueError("使用 date 模式时必须设置 CF_DELETE_DATE (格式: YYYY-MM-DD)")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)
        addrs, all_records = load_addresses_from_csv(cfg["delete_csv"], filter_date)  # 作用: 读取指定日期地址; 原理: CSV过滤读取; 专业概念: 条件查询(Conditional Query)
        targets = [(a, address_to_rule.get(a)) for a in addrs]  # 作用: 映射到规则ID; 原理: 列表推导; 专业概念: 映射(Mapping)
    elif mode == "csv":  # 作用: 从CSV删除; 原理: 条件分支; 专业概念: CSV驱动(CSV Driven)
        addrs, all_records = load_addresses_from_csv(cfg["delete_csv"])  # 作用: 读取CSV地址; 原理: CSV解析; 专业概念: CSV解析(Parsing)
        targets = [(a, address_to_rule.get(a)) for a in addrs]  # 作用: 映射到规则ID; 原理: 列表推导; 专业概念: 映射(Mapping)
    else:  # 作用: 指定地址删除; 原理: 条件分支; 专业概念: 指定删除(Targeted Delete)
        addrs = parse_address_list(cfg["delete_addresses"])  # 作用: 解析指定地址; 原理: 逗号分割; 专业概念: 解析(Parse)
        targets = [(a, address_to_rule.get(a)) for a in addrs]  # 作用: 映射到规则ID; 原理: 列表推导; 专业概念: 映射(Mapping)

    deleted_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # 作用: 获取删除时间; 原理: 格式化时间戳; 专业概念: 时间格式化(Time Formatting)
    deleted_addresses = set()  # 作用: 记录已删除地址; 原理: 集合容器; 专业概念: 集合(Set)

    for address, rule_id in targets:  # 作用: 逐条删除; 原理: 循环; 专业概念: 迭代(Iteration)
        if not rule_id:  # 作用: 处理未找到规则; 原理: 条件判断; 专业概念: 缺失(Missing)
            print(f"SKIP: {address} (未找到规则ID)")  # 作用: 输出跳过; 原理: 标准输出; 专业概念: 标准输出(stdout)
            continue  # 作用: 跳过当前项; 原理: 循环控制; 专业概念: continue(继续)
        try:  # 作用: 捕获删除错误; 原理: try/except; 专业概念: 异常处理(Exception Handling)
            resp = delete_rule(cfg["token"], cfg["zone_id"], rule_id)  # 作用: 删除规则; 原理: HTTP DELETE; 专业概念: REST调用(REST Call)
            if resp.get("success") is True:  # 作用: 判断是否成功; 原理: 读取响应字段; 专业概念: 响应结构(Response Schema)
                print(f"DELETED: {address}")  # 作用: 输出成功; 原理: 标准输出; 专业概念: 标准输出(stdout)
                deleted_addresses.add(address)  # 作用: 记录已删除地址; 原理: 集合添加; 专业概念: 集合操作(Set Operation)
            else:  # 作用: 处理失败; 原理: 条件分支; 专业概念: 错误处理(Error Handling)
                err = json.dumps(resp.get("errors", []), ensure_ascii=False)  # 作用: 格式化错误; 原理: JSON序列化; 专业概念: 诊断信息(Diagnostics)
                print(f"FAIL: {address}")  # 作用: 输出失败; 原理: 标准输出; 专业概念: 标准输出(stdout)
                print(err)  # 作用: 输出错误详情; 原理: 标准输出; 专业概念: 标准输出(stdout)
        except Exception as exc:  # 作用: 捕获异常; 原理: 异常兜底; 专业概念: 兜底异常(General Exception)
            print(f"ERROR: {address}")  # 作用: 输出异常提示; 原理: 标准输出; 专业概念: 标准输出(stdout)
            print(str(exc))  # 作用: 输出异常信息; 原理: 转字符串; 专业概念: 异常消息(Exception Message)

    # 作用: 更新CSV删除状态; 原理: 遍历记录标记已删除项; 专业概念: 状态更新(Status Update)
    if all_records and deleted_addresses:  # 作用: 检查是否需要更新CSV; 原理: 条件判断; 专业概念: 条件执行(Conditional Execution)
        for record in all_records:  # 作用: 遍历所有记录; 原理: 循环; 专业概念: 迭代(Iteration)
            if record.get("address") in deleted_addresses:  # 作用: 检查是否已删除; 原理: 集合成员判断; 专业概念: 成员检查(Membership Test)
                record["is_deleted"] = "是"  # 作用: 标记已删除; 原理: 字典赋值; 专业概念: 状态标记(Status Flag)
                record["deleted_date"] = deleted_date  # 作用: 记录删除时间; 原理: 字典赋值; 专业概念: 时间戳(Timestamp)

        # 作用: 写回CSV文件; 原理: 覆盖写入更新后的记录; 专业概念: 数据持久化(Data Persistence)
        with open(cfg["delete_csv"], "w", encoding="utf-8", newline="") as f:  # 作用: 打开CSV文件写入; 原理: 上下文管理; 专业概念: 文件IO(File I/O)
            fieldnames = ["address", "created_date", "status", "message", "is_deleted", "deleted_date"]  # 作用: 定义CSV字段; 原理: 字段列表; 专业概念: 表结构(Schema)
            writer = csv.DictWriter(f, fieldnames=fieldnames)  # 作用: 创建CSV写入器; 原理: 字段映射; 专业概念: 字段(Field)
            writer.writeheader()  # 作用: 写入表头; 原理: CSV写入; 专业概念: 表头(Header)
            writer.writerows(all_records)  # 作用: 写入所有记录; 原理: 批量写入; 专业概念: 批处理(Batch Write)
        print(f"CSV 已更新: {cfg['delete_csv']}")  # 作用: 输出更新提示; 原理: 标准输出; 专业概念: 标准输出(stdout)

    print(f"删除完成，共删除 {len(deleted_addresses)} 条记录")  # 作用: 输出统计信息; 原理: 集合长度; 专业概念: 统计(Statistics)


if __name__ == "__main__":  # 作用: 判断是否主模块; 原理: Python入口判断; 专业概念: 主模块(Main Module)
    main()  # 作用: 调用主函数; 原理: 函数调用; 专业概念: 程序入口(Entry Point)
