#!/usr/bin/env python3  # 作用: 指定解释器入口; 原理: Shebang告诉系统用哪个解释器; 专业概念: Shebang(脚本首行标识)
import csv  # 作用: 生成CSV文件; 原理: 标准库CSV写入器; 专业概念: CSV(逗号分隔值, 表格文本格式)
import json  # 作用: 处理JSON数据; 原理: 标准库序列化/反序列化; 专业概念: JSON(JavaScript Object Notation, 轻量数据格式)
import os  # 作用: 访问环境变量与文件路径; 原理: 标准库系统接口; 专业概念: OS接口(Operating System Interface, 系统交互)
import urllib.request  # 作用: 发送HTTP请求; 原理: 标准库网络请求; 专业概念: HTTP客户端(HTTP Client, 发起请求)
import urllib.error  # 作用: 处理HTTP异常; 原理: 标准库异常类型; 专业概念: 异常处理(Exception Handling, 错误控制)
from datetime import datetime  # 作用: 处理日期时间; 原理: 标准库时间模块; 专业概念: 日期时间(Datetime)


def load_env_file(env_path):  # 作用: 加载.env文件; 原理: 逐行解析键值; 专业概念: 配置文件(Configuration File, 外部参数)
    if not env_path or not os.path.isfile(env_path):  # 作用: 校验文件路径; 原理: 条件判断+文件存在检查; 专业概念: 文件系统(File System)
        return {}  # 作用: 返回空配置; 原理: 早退出; 专业概念: 空字典(Empty Dict)
    data = {}  # 作用: 初始化配置容器; 原理: 字典存储键值; 专业概念: 字典(Dictionary)
    with open(env_path, "r", encoding="utf-8") as f:  # 作用: 打开文件读取; 原理: 上下文管理; 专业概念: 上下文管理(Context Manager)
        for raw in f:  # 作用: 逐行读取; 原理: 迭代遍历; 专业概念: 迭代(Iteration)
            line = raw.strip()  # 作用: 去除空白; 原理: 字符串裁剪; 专业概念: 字符串处理(String Processing)
            if not line or line.startswith("#"):  # 作用: 跳过空行/注释; 原理: 条件判断; 专业概念: 注释(Comment, 非执行内容)
                continue  # 作用: 进入下一行; 原理: 循环控制; 专业概念: continue(继续)
            if "=" not in line:  # 作用: 过滤非法行; 原理: 字符串包含判断; 专业概念: 格式校验(Validation)
                continue  # 作用: 忽略非法行; 原理: 循环控制; 专业概念: continue(继续)
            key, value = line.split("=", 1)  # 作用: 分离键和值; 原理: 字符串分割; 专业概念: 解析(Parse)
            data[key.strip()] = value.strip()  # 作用: 保存键值; 原理: 字典赋值; 专业概念: 映射(Mapping)
    return data  # 作用: 返回配置; 原理: 函数返回; 专业概念: 返回值(Return Value)


def get_config():  # 作用: 获取配置; 原理: 环境变量优先+ .env 兜底; 专业概念: 配置合并(Configuration Merge)
    env_path = os.getenv("CF_ENV_FILE", ".env")  # 作用: 读取.env路径; 原理: 读取环境变量; 专业概念: 环境变量(Environment Variable)
    file_env = load_env_file(env_path)  # 作用: 读取.env内容; 原理: 调用解析函数; 专业概念: 函数调用(Function Call)
    def pick(key, default=""):  # 作用: 获取配置值; 原理: 本地函数封装; 专业概念: 闭包(Closure)
        return os.getenv(key, file_env.get(key, default))  # 作用: 按优先级取值; 原理: 覆盖; 专业概念: 覆盖(Override)
    return {  # 作用: 统一输出配置; 原理: 字典组装; 专业概念: 配置对象(Configuration Object)
        "token": pick("CF_API_TOKEN"),  # 作用: 读取API令牌; 原理: 配置映射; 专业概念: 认证令牌(Token)
        "zone_id": pick("CF_ZONE_ID"),  # 作用: 读取Zone ID; 原理: 配置映射; 专业概念: 区域ID(Zone ID)
        "output_csv": pick("CF_LIST_OUTPUT", "email_list.csv"),  # 作用: 读取输出文件路径; 原理: 配置映射; 专业概念: 文件路径(Path)
    }  # 作用: 结束配置字典; 原理: 字面量结束; 专业概念: 字典(Dictionary)


def request_json(url, token, method="GET"):  # 作用: 发送HTTP请求; 原理: urllib封装请求; 专业概念: HTTP请求(HTTP Request)
    req = urllib.request.Request(url, method=method)  # 作用: 构造请求对象; 原理: 请求封装; 专业概念: 请求对象(Request Object)
    req.add_header("Authorization", f"Bearer {token}")  # 作用: 添加认证头; 原理: Bearer认证; 专业概念: 认证(Authorization)
    req.add_header("Content-Type", "application/json")  # 作用: 指定内容类型; 原理: HTTP头; 专业概念: MIME类型(MIME Type)
    try:  # 作用: 捕获HTTP异常; 原理: try/except; 专业概念: 异常处理(Exception Handling)
        with urllib.request.urlopen(req, timeout=30) as resp:  # 作用: 发起请求并读取响应; 原理: URL打开器; 专业概念: 超时(Timeout)
            body = resp.read().decode("utf-8")  # 作用: 读取响应内容; 原理: 解码; 专业概念: 解码(Decoding)
            return json.loads(body)  # 作用: 解析JSON; 原理: 反序列化; 专业概念: 反序列化(Deserialization)
    except urllib.error.HTTPError as exc:  # 作用: 捕获HTTP错误; 原理: 异常分支; 专业概念: HTTPError(HTTP错误)
        detail = exc.read().decode("utf-8")  # 作用: 读取错误响应; 原理: 读取错误流; 专业概念: 错误响应(Error Response)
        raise RuntimeError(detail) from exc  # 作用: 抛出运行错误; 原理: 异常包装; 专业概念: 异常包装(Exception Wrapping)


def list_all_rules(token, zone_id):  # 作用: 拉取全部邮箱规则; 原理: 分页请求; 专业概念: 分页(Pagination)
    api_base = "https://api.cloudflare.com/client/v4"  # 作用: API基础地址; 原理: 常量配置; 专业概念: 端点(Endpoint)
    page = 1  # 作用: 初始化页码; 原理: 变量赋值; 专业概念: 页码(Page)
    per_page = 50  # 作用: 设置每页数量; 原理: 常量; 专业概念: 分页大小(Page Size)
    rules = []  # 作用: 收集规则; 原理: 列表容器; 专业概念: 列表(List)
    while True:  # 作用: 轮询分页; 原理: 循环; 专业概念: while循环(While Loop)
        url = f"{api_base}/zones/{zone_id}/email/routing/rules?page={page}&per_page={per_page}"  # 作用: 拼接列表接口; 原理: 字符串插值; 专业概念: API路径(API Path)
        print(f"正在获取第 {page} 页...")  # 作用: 输出进度; 原理: 标准输出; 专业概念: 标准输出(stdout)
        resp = request_json(url, token, method="GET")  # 作用: 请求规则列表; 原理: HTTP GET; 专业概念: REST调用(REST Call)
        if not resp.get("success"):  # 作用: 检查API调用是否成功; 原理: 条件判断; 专业概念: 响应校验(Response Validation)
            errors = json.dumps(resp.get("errors", []), ensure_ascii=False)  # 作用: 格式化错误; 原理: JSON序列化; 专业概念: 错误处理(Error Handling)
            raise RuntimeError(f"API 调用失败: {errors}")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 异常(Exception)
        items = resp.get("result", [])  # 作用: 读取结果; 原理: 字典取值; 专业概念: 响应体(Response Body)
        rules.extend(items)  # 作用: 合并规则; 原理: 列表扩展; 专业概念: 扩展(Extend)
        result_info = resp.get("result_info", {})  # 作用: 读取分页信息; 原理: 字典取值; 专业概念: 元数据(Metadata)
        total_pages = result_info.get("total_pages", page)  # 作用: 获取总页数; 原理: 字典取值; 专业概念: 总页数(Total Pages)
        if page >= total_pages:  # 作用: 判断是否结束; 原理: 比较; 专业概念: 终止条件(Termination Condition)
            break  # 作用: 退出循环; 原理: 循环控制; 专业概念: break(跳出循环)
        page += 1  # 作用: 下一页; 原理: 递增; 专业概念: 自增(Increment)
    return rules  # 作用: 返回规则列表; 原理: 函数返回; 专业概念: 返回值(Return Value)


def parse_rule_to_record(rule):  # 作用: 解析规则为CSV记录; 原理: 提取关键字段; 专业概念: 数据转换(Data Transformation)
    rule_id = rule.get("id", "")  # 作用: 获取规则ID; 原理: 字典取值; 专业概念: 标识符(Identifier)
    rule_name = rule.get("name", "")  # 作用: 获取规则名称; 原理: 字典取值; 专业概念: 名称(Name)
    enabled = rule.get("enabled", False)  # 作用: 获取启用状态; 原理: 字典取值; 专业概念: 布尔值(Boolean)
    priority = rule.get("priority", 0)  # 作用: 获取优先级; 原理: 字典取值; 专业概念: 优先级(Priority)

    # 作用: 提取邮箱地址(from matchers); 原理: 遍历匹配器找to字段; 专业概念: 数据提取(Data Extraction)
    email_address = ""  # 作用: 初始化邮箱地址; 原理: 空字符串; 专业概念: 初始化(Initialization)
    for matcher in rule.get("matchers", []):  # 作用: 遍历匹配器; 原理: 循环; 专业概念: 迭代(Iteration)
        if matcher.get("field") == "to" and matcher.get("type") == "literal":  # 作用: 过滤收件人匹配; 原理: 条件判断; 专业概念: 过滤(Filter)
            email_address = matcher.get("value", "")  # 作用: 获取邮箱地址; 原理: 字典取值; 专业概念: 值(Value)
            break  # 作用: 找到后退出循环; 原理: 循环控制; 专业概念: break(跳出)

    # 作用: 提取转发目标(from actions); 原理: 遍历动作找forward类型; 专业概念: 数据提取(Data Extraction)
    forward_to = []  # 作用: 初始化转发目标列表; 原理: 列表容器; 专业概念: 列表(List)
    for action in rule.get("actions", []):  # 作用: 遍历动作; 原理: 循环; 专业概念: 迭代(Iteration)
        if action.get("type") == "forward":  # 作用: 过滤转发动作; 原理: 条件判断; 专业概念: 过滤(Filter)
            forward_to.extend(action.get("value", []))  # 作用: 收集转发地址; 原理: 列表扩展; 专业概念: 扩展(Extend)

    forward_to_str = ", ".join(forward_to)  # 作用: 转发地址列表转字符串; 原理: 字符串拼接; 专业概念: 字符串拼接(String Join)

    return {  # 作用: 返回记录字典; 原理: 字典字面量; 专业概念: 记录对象(Record Object)
        "rule_id": rule_id,  # 作用: 规则ID; 原理: 字段赋值; 专业概念: 字段(Field)
        "email_address": email_address,  # 作用: 邮箱地址; 原理: 字段赋值; 专业概念: 字段(Field)
        "rule_name": rule_name,  # 作用: 规则名称; 原理: 字段赋值; 专业概念: 字段(Field)
        "enabled": "是" if enabled else "否",  # 作用: 启用状态; 原理: 三元表达式; 专业概念: 条件表达式(Conditional Expression)
        "priority": priority,  # 作用: 优先级; 原理: 字段赋值; 专业概念: 字段(Field)
        "forward_to": forward_to_str,  # 作用: 转发目标; 原理: 字段赋值; 专业概念: 字段(Field)
    }  # 作用: 结束记录对象; 原理: 字典结束; 专业概念: 字典(Dictionary)


def main():  # 作用: 程序入口; 原理: 主函数组织流程; 专业概念: 主函数(Main Function)
    cfg = get_config()  # 作用: 读取配置; 原理: 调用配置函数; 专业概念: 配置读取(Configuration Load)

    # 作用: 校验必填参数; 原理: 条件判断; 专业概念: 参数校验(Parameter Validation)
    if not cfg["token"] or not cfg["zone_id"]:  # 作用: 检查必填项; 原理: 条件判断; 专业概念: 非空检查(Non-Empty Check)
        raise ValueError("请设置 CF_API_TOKEN 和 CF_ZONE_ID")  # 作用: 抛出错误; 原理: 异常抛出; 专业概念: 参数校验(Parameter Validation)

    print("开始获取邮箱规则列表...")  # 作用: 输出提示; 原理: 标准输出; 专业概念: 标准输出(stdout)
    rules = list_all_rules(cfg["token"], cfg["zone_id"])  # 作用: 获取所有规则; 原理: API调用; 专业概念: 数据获取(Data Fetching)
    print(f"共获取到 {len(rules)} 条规则")  # 作用: 输出统计; 原理: 列表长度; 专业概念: 统计(Statistics)

    if not rules:  # 作用: 检查是否有规则; 原理: 条件判断; 专业概念: 空值检查(Empty Check)
        print("当前账户没有任何邮箱规则")  # 作用: 输出提示; 原理: 标准输出; 专业概念: 标准输出(stdout)
        return  # 作用: 退出程序; 原理: 函数返回; 专业概念: 早退出(Early Return)

    # 作用: 转换规则为CSV记录; 原理: 列表推导; 专业概念: 数据转换(Data Transformation)
    records = [parse_rule_to_record(rule) for rule in rules]  # 作用: 解析所有规则; 原理: 列表推导; 专业概念: 映射(Mapping)

    # 作用: 写入CSV文件; 原理: CSV写入器; 专业概念: 数据持久化(Data Persistence)
    output_csv = cfg["output_csv"]  # 作用: 获取输出路径; 原理: 字典取值; 专业概念: 路径(Path)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # 作用: 获取当前时间; 原理: 格式化时间戳; 专业概念: 时间格式化(Time Formatting)

    with open(output_csv, "w", encoding="utf-8", newline="") as f:  # 作用: 打开CSV文件写入; 原理: 上下文管理; 专业概念: 文件IO(File I/O)
        fieldnames = ["rule_id", "email_address", "rule_name", "enabled", "priority", "forward_to"]  # 作用: 定义CSV字段; 原理: 字段列表; 专业概念: 表结构(Schema)
        writer = csv.DictWriter(f, fieldnames=fieldnames)  # 作用: 创建CSV写入器; 原理: 字段映射; 专业概念: 字段(Field)
        writer.writeheader()  # 作用: 写入表头; 原理: CSV写入; 专业概念: 表头(Header)
        writer.writerows(records)  # 作用: 写入所有记录; 原理: 批量写入; 专业概念: 批处理(Batch Write)

    print(f"✓ CSV 已生成: {output_csv}")  # 作用: 输出成功提示; 原理: 标准输出; 专业概念: 标准输出(stdout)
    print(f"✓ 导出时间: {timestamp}")  # 作用: 输出时间戳; 原理: 标准输出; 专业概念: 标准输出(stdout)
    print(f"✓ 总计规则: {len(records)} 条")  # 作用: 输出统计; 原理: 列表长度; 专业概念: 统计(Statistics)

    # 作用: 统计启用和禁用数量; 原理: 列表推导+长度; 专业概念: 数据统计(Data Statistics)
    enabled_count = len([r for r in records if r["enabled"] == "是"])  # 作用: 统计启用数量; 原理: 过滤+计数; 专业概念: 过滤统计(Filter Count)
    disabled_count = len(records) - enabled_count  # 作用: 计算禁用数量; 原理: 减法; 专业概念: 差值(Difference)
    print(f"  - 已启用: {enabled_count} 条")  # 作用: 输出启用数量; 原理: 标准输出; 专业概念: 标准输出(stdout)
    print(f"  - 已禁用: {disabled_count} 条")  # 作用: 输出禁用数量; 原理: 标准输出; 专业概念: 标准输出(stdout)


if __name__ == "__main__":  # 作用: 判断是否主模块; 原理: Python入口判断; 专业概念: 主模块(Main Module)
    main()  # 作用: 调用主函数; 原理: 函数调用; 专业概念: 程序入口(Entry Point)
