$ErrorActionPreference = "Stop" # 作用: 遇到错误立即停止脚本; 原理: 设置全局错误策略; 专业概念: 错误处理(Error Handling, 控制异常流程)
$token = $env:CF_API_TOKEN # 作用: 读取API令牌; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$zoneId = $env:CF_ZONE_ID # 作用: 读取区域ID; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$domain = $env:CF_DOMAIN # 作用: 读取域名; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$destEmail = $env:CF_DEST_EMAIL # 作用: 读取目标邮箱; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$inputFile = $env:CF_INPUT_FILE # 作用: 读取输入文件路径; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$prefix = $env:CF_PREFIX # 作用: 读取地址前缀; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$startRaw = $env:CF_START # 作用: 读取起始序号文本; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$countRaw = $env:CF_COUNT # 作用: 读取生成数量文本; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$delayRaw = $env:CF_DELAY_MS # 作用: 读取延迟毫秒文本; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
$ruleEnabledRaw = $env:CF_RULE_ENABLED # 作用: 读取规则启用开关; 原理: 访问进程环境变量; 专业概念: 环境变量(Environment Variable, 进程级键值对)
if (-not $token) { # 作用: 校验令牌是否缺失; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    Write-Error "请设置 CF_API_TOKEN" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束令牌校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
if (-not $zoneId) { # 作用: 校验区域ID是否缺失; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    Write-Error "请设置 CF_ZONE_ID" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束区域ID校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
if (-not $destEmail) { # 作用: 校验目标邮箱是否缺失; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    Write-Error "请设置 CF_DEST_EMAIL" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束目标邮箱校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
if (-not $inputFile -and (-not $prefix -or -not $countRaw)) { # 作用: 校验输入来源是否有效; 原理: 逻辑组合判断; 专业概念: 逻辑运算(Logic Operation, 与/或判断)
    Write-Error "请设置 CF_INPUT_FILE 或 CF_PREFIX+CF_COUNT" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束输入来源校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
if (-not $inputFile -and -not $domain) { # 作用: 校验前缀模式必须有域名; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    Write-Error "使用前缀生成时必须设置 CF_DOMAIN" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束域名校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
if ($inputFile -and -not (Test-Path -LiteralPath $inputFile)) { # 作用: 校验输入文件是否存在; 原理: 文件系统判断; 专业概念: 文件路径(File Path, 文件位置标识)
    Write-Error "找不到输入文件: $inputFile" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束输入文件校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
$ruleEnabled = $true # 作用: 初始化规则启用状态; 原理: 变量赋值; 专业概念: 变量(Variable, 存储数据的名字)
if ($ruleEnabledRaw -eq "false") { # 作用: 解析禁用开关; 原理: 字符串比较; 专业概念: 比较运算(Comparison, 判断相等)
    $ruleEnabled = $false # 作用: 设置规则为禁用; 原理: 变量赋值; 专业概念: 布尔值(Boolean, 真/假)
} # 作用: 结束启用开关解析分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
$start = 1 # 作用: 设置默认起始序号; 原理: 变量赋值; 专业概念: 默认值(Default, 缺省参数)
if ($startRaw) { # 作用: 判断是否提供起始序号; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    $start = [int]$startRaw # 作用: 转换起始序号为整数; 原理: 类型转换; 专业概念: 类型转换(Type Casting, 改变数据类型)
} # 作用: 结束起始序号解析分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
$count = 0 # 作用: 初始化生成数量; 原理: 变量赋值; 专业概念: 变量(Variable, 存储数据的名字)
if ($countRaw) { # 作用: 判断是否提供生成数量; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    $count = [int]$countRaw # 作用: 转换生成数量为整数; 原理: 类型转换; 专业概念: 类型转换(Type Casting, 改变数据类型)
} # 作用: 结束生成数量解析分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
if (-not $inputFile -and $count -le 0) { # 作用: 校验数量必须为正; 原理: 数值比较; 专业概念: 比较运算(Comparison, 判断大小)
    Write-Error "CF_COUNT 必须为正数" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束数量校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
$delayMs = 0 # 作用: 初始化请求间隔; 原理: 变量赋值; 专业概念: 变量(Variable, 存储数据的名字)
if ($delayRaw) { # 作用: 判断是否提供延迟; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    $delayMs = [int]$delayRaw # 作用: 转换延迟为整数; 原理: 类型转换; 专业概念: 类型转换(Type Casting, 改变数据类型)
} # 作用: 结束延迟解析分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
$addresses = @() # 作用: 创建地址列表容器; 原理: 线性集合存储; 专业概念: 数组(Array, 有序集合)
if ($inputFile) { # 作用: 选择文件输入模式; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    $lines = Get-Content -LiteralPath $inputFile # 作用: 读取文件所有行; 原理: 文件IO读取; 专业概念: 文件IO(File I/O, 读写文件)
    foreach ($line in $lines) { # 作用: 逐行遍历输入; 原理: 迭代控制; 专业概念: 循环(Loop, 重复执行)
        $trim = $line.Trim() # 作用: 去除空白字符; 原理: 字符串处理; 专业概念: 字符串(String, 文本数据)
        if (-not $trim) { # 作用: 判断是否空行; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
            continue # 作用: 跳过本次循环; 原理: 循环控制语句; 专业概念: continue(Continue, 继续下一次循环)
        } # 作用: 结束空行判断分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
        if ($trim -like "*@*") { # 作用: 判断是否完整邮箱; 原理: 通配符匹配; 专业概念: 模式匹配(Pattern Matching, 规则匹配)
            $address = $trim # 作用: 使用完整邮箱; 原理: 变量赋值; 专业概念: 变量(Variable, 存储数据的名字)
        } else { # 作用: 处理本地部分模式; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
            if (-not $domain) { # 作用: 校验域名是否提供; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
                Write-Error "输入文件中有本地部分但未设置 CF_DOMAIN" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
                exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
            } # 作用: 结束域名校验分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
            $address = "$trim@$domain" # 作用: 拼接完整邮箱; 原理: 字符串插值; 专业概念: 字符串插值(String Interpolation, 模板替换)
        } # 作用: 结束邮箱格式判断分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
        $addresses += $address # 作用: 追加到地址列表; 原理: 动态数组扩展; 专业概念: 追加(Append, 向集合添加元素)
    } # 作用: 结束逐行遍历; 原理: 迭代控制; 专业概念: 循环(Loop, 重复执行)
} else { # 作用: 选择前缀生成模式; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
    for ($i = 0; $i -lt $count; $i++) { # 作用: 按数量循环生成; 原理: 计数循环; 专业概念: for循环(For Loop, 计数迭代)
        $num = $start + $i # 作用: 计算序号; 原理: 数值加法; 专业概念: 算术运算(Arithmetic, 数值计算)
        $address = "$prefix$num@$domain" # 作用: 拼接完整邮箱; 原理: 字符串插值; 专业概念: 字符串插值(String Interpolation, 模板替换)
        $addresses += $address # 作用: 追加到地址列表; 原理: 动态数组扩展; 专业概念: 追加(Append, 向集合添加元素)
    } # 作用: 结束前缀生成循环; 原理: 迭代控制; 专业概念: 循环(Loop, 重复执行)
} # 作用: 结束输入模式选择; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
if ($addresses.Count -eq 0) { # 作用: 校验地址列表非空; 原理: 数值比较; 专业概念: 集合计数(Collection Count, 元素数量)
    Write-Error "未生成任何地址" # 作用: 输出错误提示; 原理: 写入错误流; 专业概念: 标准错误流(stderr, 错误信息通道)
    exit 1 # 作用: 中止脚本执行; 原理: 进程退出码; 专业概念: 退出码(Exit Code, 0成功/非0失败)
} # 作用: 结束地址数量校验; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
$apiBase = "https://api.cloudflare.com/client/v4" # 作用: 设置API基础地址; 原理: 常量字符串配置; 专业概念: 端点(Endpoint, 服务访问地址)
$headers = @{ # 作用: 创建请求头集合; 原理: 键值映射存储; 专业概念: 哈希表(Hash Table, 键值映射)
    "Authorization" = "Bearer $token" # 作用: 携带认证令牌; 原理: Bearer认证头; 专业概念: 认证(Authorization, 身份校验)
    "Content-Type" = "application/json" # 作用: 声明JSON格式; 原理: HTTP头告知类型; 专业概念: MIME类型(MIME Type, 内容格式标识)
} # 作用: 结束请求头集合; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
$endpoint = "$apiBase/zones/$zoneId/email/routing/rules" # 作用: 拼接规则创建接口; 原理: 字符串插值; 专业概念: 接口路径(API Path, 资源地址)
foreach ($address in $addresses) { # 作用: 逐个创建规则; 原理: 迭代控制; 专业概念: 循环(Loop, 重复执行)
    $bodyObject = @{ # 作用: 构造请求体对象; 原理: 键值映射组织数据; 专业概念: 对象(Object, 数据结构)
        name = "bulk:$address" # 作用: 设置规则名称; 原理: 字符串赋值; 专业概念: 规则名(Rule Name, 规则标识)
        enabled = $ruleEnabled # 作用: 设置启用状态; 原理: 布尔赋值; 专业概念: 布尔值(Boolean, 真/假)
        matchers = @( # 作用: 设置匹配条件列表; 原理: 数组组合; 专业概念: 数组(Array, 有序集合)
            @{ # 作用: 创建匹配器对象; 原理: 键值映射组织数据; 专业概念: 对象(Object, 数据结构)
                type = "literal" # 作用: 设定精确匹配; 原理: 常量赋值; 专业概念: 精确匹配(Literal Match, 完整相等)
                field = "to" # 作用: 指定匹配字段; 原理: 常量赋值; 专业概念: 字段(Field, 数据属性)
                value = $address # 作用: 指定目标地址; 原理: 变量引用; 专业概念: 引用(Reference, 使用已有值)
            } # 作用: 结束匹配器对象; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
        ) # 作用: 结束匹配器列表; 原理: 数组结束标记; 专业概念: 数组(Array, 有序集合)
        actions = @( # 作用: 设置动作列表; 原理: 数组组合; 专业概念: 数组(Array, 有序集合)
            @{ # 作用: 创建动作对象; 原理: 键值映射组织数据; 专业概念: 对象(Object, 数据结构)
                type = "forward" # 作用: 指定转发动作; 原理: 常量赋值; 专业概念: 动作(Action, 处理方式)
                value = @($destEmail) # 作用: 指定转发目标; 原理: 数组包装; 专业概念: 列表(List, 多值集合)
            } # 作用: 结束动作对象; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
        ) # 作用: 结束动作列表; 原理: 数组结束标记; 专业概念: 数组(Array, 有序集合)
    } # 作用: 结束请求体对象; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
    $bodyJson = $bodyObject | ConvertTo-Json -Depth 6 # 作用: 转换为JSON字符串; 原理: 序列化; 专业概念: JSON(JavaScript Object Notation, 轻量数据格式)
    try { # 作用: 开始异常捕获块; 原理: try/catch结构; 专业概念: 异常(Exception, 运行时错误)
        $resp = Invoke-RestMethod -Method Post -Uri $endpoint -Headers $headers -Body $bodyJson # 作用: 发送创建请求; 原理: HTTP通信; 专业概念: HTTP请求(HTTP Request, 客户端调用服务)
        if ($resp.success -eq $true) { # 作用: 判断接口是否成功; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
            Write-Host "OK: $address" # 作用: 输出成功信息; 原理: 标准输出; 专业概念: 标准输出(stdout, 正常信息通道)
        } else { # 作用: 处理失败分支; 原理: 条件分支判断; 专业概念: 条件判断(Condition, 真/假分支)
            Write-Host "FAIL: $address" # 作用: 输出失败信息; 原理: 标准输出; 专业概念: 标准输出(stdout, 正常信息通道)
            Write-Host ($resp.errors | ConvertTo-Json -Depth 6) # 作用: 打印错误详情; 原理: 序列化错误对象; 专业概念: 诊断信息(Diagnostics, 排错数据)
        } # 作用: 结束成功失败分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
    } catch { # 作用: 捕获调用异常; 原理: catch捕获异常; 专业概念: 异常(Exception, 运行时错误)
        Write-Host "ERROR: $address" # 作用: 输出异常提示; 原理: 标准输出; 专业概念: 标准输出(stdout, 正常信息通道)
        Write-Host $_.Exception.Message # 作用: 输出异常原因; 原理: 读取异常对象; 专业概念: 异常对象(Exception Object, 错误载体)
    } # 作用: 结束异常捕获块; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
    if ($delayMs -gt 0) { # 作用: 判断是否需要延迟; 原理: 数值比较; 专业概念: 速率限制(Rate Limit, 限制请求频率)
        Start-Sleep -Milliseconds $delayMs # 作用: 暂停一段时间; 原理: 线程休眠; 专业概念: 延时(Delay, 控制节奏)
    } # 作用: 结束延迟判断分支; 原理: 代码块边界; 专业概念: 代码块(Block, 逻辑分组)
} # 作用: 结束规则创建循环; 原理: 迭代控制; 专业概念: 循环(Loop, 重复执行)
